// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        //return windows;
        return windows;
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLwLz3vrzkEdGlwbt9LQ2lsY4vof8mNsI',
    appId: '1:713273325829:windows:3afb6e7632ff28a6849f6c',
    messagingSenderId: '713273325829',
    projectId: 'dtitry2',
    authDomain: 'dtitry2.firebaseapp.com',
    storageBucket: 'dtitry2.appspot.com',
    // measurementId: 'G-____________',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLwLz3vrzkEdGlwbt9LQ2lsY4vof8mNsI',
    appId: '1:713273325829:web:3afb6e7632ff28a6849f6c',
    messagingSenderId: '713273325829',
    projectId: 'dtitry2',
    authDomain: 'dtitry2.firebaseapp.com',
    storageBucket: 'dtitry2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvULnFFBWQUrXxAE9O9dpR8D5jUG129K8',
    appId: '1:713273325829:android:22d49fcae3628b70849f6c',
    messagingSenderId: '713273325829',
    projectId: 'dtitry2',
    storageBucket: 'dtitry2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Y9pnEYHuiFNPx5BKHWRCGKtosXoiOT4',
    appId: '1:713273325829:ios:10cbfa75f58b7f64849f6c',
    messagingSenderId: '713273325829',
    projectId: 'dtitry2',
    storageBucket: 'dtitry2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Y9pnEYHuiFNPx5BKHWRCGKtosXoiOT4',
    appId: '1:713273325829:ios:9fe91d277883dbbb849f6c',
    messagingSenderId: '713273325829',
    projectId: 'dtitry2',
    storageBucket: 'dtitry2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
